In [195]:
import pandas as pd
import numpy as np
import seaborn as sb
import matplotlib.pyplot as plt

In [6]:
abalone = pd.read_csv('https://raw.githubusercontent.com/dsrscientist/dataset1/master/abalone.csv')

In [7]:
print(abalone.head())

  Sex  Length  Diameter  Height  Whole weight  Shucked weight  Viscera weight  \
0   M   0.455     0.365   0.095        0.5140          0.2245          0.1010   
1   M   0.350     0.265   0.090        0.2255          0.0995          0.0485   
2   F   0.530     0.420   0.135        0.6770          0.2565          0.1415   
3   M   0.440     0.365   0.125        0.5160          0.2155          0.1140   
4   I   0.330     0.255   0.080        0.2050          0.0895          0.0395   

   Shell weight  Rings  
0         0.150     15  
1         0.070      7  
2         0.210      9  
3         0.155     10  
4         0.055      7  


In [8]:
print(abalone.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4177 entries, 0 to 4176
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Sex             4177 non-null   object 
 1   Length          4177 non-null   float64
 2   Diameter        4177 non-null   float64
 3   Height          4177 non-null   float64
 4   Whole weight    4177 non-null   float64
 5   Shucked weight  4177 non-null   float64
 6   Viscera weight  4177 non-null   float64
 7   Shell weight    4177 non-null   float64
 8   Rings           4177 non-null   int64  
dtypes: float64(7), int64(1), object(1)
memory usage: 293.8+ KB
None


In [9]:
print(abalone.describe())

            Length     Diameter       Height  Whole weight  Shucked weight  \
count  4177.000000  4177.000000  4177.000000   4177.000000     4177.000000   
mean      0.523992     0.407881     0.139516      0.828742        0.359367   
std       0.120093     0.099240     0.041827      0.490389        0.221963   
min       0.075000     0.055000     0.000000      0.002000        0.001000   
25%       0.450000     0.350000     0.115000      0.441500        0.186000   
50%       0.545000     0.425000     0.140000      0.799500        0.336000   
75%       0.615000     0.480000     0.165000      1.153000        0.502000   
max       0.815000     0.650000     1.130000      2.825500        1.488000   

       Viscera weight  Shell weight        Rings  
count     4177.000000   4177.000000  4177.000000  
mean         0.180594      0.238831     9.933684  
std          0.109614      0.139203     3.224169  
min          0.000500      0.001500     1.000000  
25%          0.093500      0.130000     8.

In [11]:
abalone.head(10)

Sex  Length  Diameter  Height  Whole weight  Shucked weight  Viscera weight  \
0   M   0.455     0.365   0.095        0.5140          0.2245          0.1010   
1   M   0.350     0.265   0.090        0.2255          0.0995          0.0485   
2   F   0.530     0.420   0.135        0.6770          0.2565          0.1415   
3   M   0.440     0.365   0.125        0.5160          0.2155          0.1140   
4   I   0.330     0.255   0.080        0.2050          0.0895          0.0395   
5   I   0.425     0.300   0.095        0.3515          0.1410          0.0775   
6   F   0.530     0.415   0.150        0.7775          0.2370          0.1415   
7   F   0.545     0.425   0.125        0.7680          0.2940          0.1495   
8   M   0.475     0.370   0.125        0.5095          0.2165          0.1125   
9   F   0.550     0.440   0.150        0.8945          0.3145          0.1510   

   Shell weight  Rings  
0         0.150     15  
1         0.070      7  
2         0.210      9  
3         0.155     10  
4         0.055      7  
5         0.120      8  
6         0.330     20  
7         0.260     16  
8         0.165      9  
9         0.320     19

In [12]:
ab1=abalone.copy()

In [13]:
ab1.isnull().sum(axis=0)

Sex               0
Length            0
Diameter          0
Height            0
Whole weight      0
Shucked weight    0
Viscera weight    0
Shell weight      0
Rings             0
dtype: int64

In [16]:
ab1_all = ab1.drop(columns="Rings")
target = ab1['Rings']

In [18]:
ab1_all = pd.get_dummies(ab1_all)
ab1_all.columns

Index(['Length', 'Diameter', 'Height', 'Whole weight', 'Shucked weight',
       'Viscera weight', 'Shell weight', 'Sex_F', 'Sex_I', 'Sex_M'],
      dtype='object')

In [21]:
ab1_all.shape

(4177, 10)

In [22]:
target.value_counts()

9     689
10    634
8     568
11    487
7     391
12    267
6     259
13    203
14    126
5     115
15    103
16     67
17     58
4      57
18     42
19     32
20     26
3      15
21     14
23      9
22      6
27      2
24      2
1       1
26      1
29      1
2       1
25      1
Name: Rings, dtype: int64

In [24]:
from sklearn import preprocessing
ab1_unscaled = ab1_all.values
ab1_minmax = preprocessing.MinMaxScaler().fit_transform(ab1_unscaled)

In [26]:
from sklearn.neighbors import KNeighborsClassifier
clf = KNeighborsClassifier(n_neighbors=1)

In [29]:
from sklearn.model_selection import KFold, RepeatedStratifiedKFold, StratifiedKFold
cv_method = RepeatedStratifiedKFold(n_splits=5,
                                   n_repeats=3,
                                   random_state=999)

In [33]:
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import MinMaxScaler
scoring_metric = 'accuracy'
cv_results_full = cross_val_score(estimator=clf,
                                 X=ab1_minmax,
                                 y=target,
                                 cv=cv_method,
                                 scoring=scoring_metric)

C:\Users\HUCON SOLUTIONS PVT\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:666: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(("The least populated class in y has only %d"
C:\Users\HUCON SOLUTIONS PVT\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:666: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(("The least populated class in y has only %d"
C:\Users\HUCON SOLUTIONS PVT\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:666: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(("The least populated class in y has only %d"


In [34]:
cv_results_full

array([0.19258373, 0.20813397, 0.2       , 0.21077844, 0.21916168,
       0.19856459, 0.20454545, 0.21317365, 0.19041916, 0.2011976 ,
       0.21172249, 0.20813397, 0.19161677, 0.18323353, 0.19401198])

In [35]:
cv_results_full.mean().round(4)

0.2018

In [ ]:
#F Score

In [36]:
num_features = 10

In [38]:
from sklearn import feature_selection as fs
fs_fit_fscore = fs.SelectKBest(fs.f_classif, k=num_features)
fs_fit_fscore.fit_transform(ab1_minmax, target)
fs_indices_fscore = np.argsort(fs_fit_fscore.scores_)[::-1][0:num_features]
fs_indices_fscore

array([1, 0, 6, 2, 3, 5, 4, 8, 7, 9], dtype=int64)

In [39]:
ab1_all.dtypes

Length            float64
Diameter          float64
Height            float64
Whole weight      float64
Shucked weight    float64
Viscera weight    float64
Shell weight      float64
Sex_F               uint8
Sex_I               uint8
Sex_M               uint8
dtype: object

In [40]:
best_features_fscore = ab1_all.columns[fs_indices_fscore].values
best_features_fscore

array(['Diameter', 'Length', 'Shell weight', 'Height', 'Whole weight',
       'Viscera weight', 'Shucked weight', 'Sex_I', 'Sex_F', 'Sex_M'],
      dtype=object)

In [41]:
feature_importances_fscore = fs_fit_fscore.scores_[fs_indices_fscore]
feature_importances_fscore

array([196.43610528, 188.50942458, 147.23694566, 124.42771441,
       113.71233973, 103.72143783,  80.79767682,  68.87047717,
        15.78351983,  10.62934022])

In [80]:
!pip install altair

In [82]:
import altair as alt

In [83]:
def plot_imp(best_features, scores, method_name, color):
 
 abalone = pd.DataFrame({'features': best_features,
 'importances': scores})
 
 chart = alt.Chart(abalone,
 width=500,
 title=method_name + ' Feature Importances'
 ).mark_bar(opacity=0.75,
 color=color).encode(
 alt.X('features', title='Feature', sort=None, axis=alt.AxisConfig(labelAngle=45)),
 alt.Y('importances', title='Importance')
 )
 
 return chart

In [84]:
cv_results_fscore = cross_val_score(estimator=clf,
 X=ab1_minmax[:, fs_indices_fscore[:8]],
 y=target,
 cv=cv_method,
 scoring=scoring_metric)
cv_results_fscore.mean().round(4)

C:\Users\HUCON SOLUTIONS PVT\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:666: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(("The least populated class in y has only %d"
C:\Users\HUCON SOLUTIONS PVT\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:666: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(("The least populated class in y has only %d"
C:\Users\HUCON SOLUTIONS PVT\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:666: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(("The least populated class in y has only %d"


0.2025

In [85]:
plot_imp(best_features_fscore, feature_importances_fscore, 'F-Score', 'blue')

alt.Chart(...)

In [ ]:
#fs using mutual information

In [54]:
fs_fit_mutual_info = fs.SelectKBest(fs.mutual_info_classif, k=num_features)
fs_fit_mutual_info.fit_transform(ab1_minmax, target)
fs_indices_mutual_info = np.argsort(fs_fit_mutual_info.scores_)[::-1][0:num_features]
best_features_mutual_info = ab1_all.columns[fs_indices_mutual_info].values
best_features_mutual_info

array(['Shell weight', 'Diameter', 'Height', 'Whole weight',
       'Viscera weight', 'Length', 'Shucked weight', 'Sex_I', 'Sex_F',
       'Sex_M'], dtype=object)

In [55]:
feature_importances_mutual_info = fs_fit_mutual_info.scores_[fs_indices_mutual_info]
feature_importances_mutual_info

array([0.45954723, 0.40479394, 0.38949394, 0.38897483, 0.37867451,
       0.37074299, 0.32874121, 0.15257082, 0.06772601, 0.03799386])

In [59]:
cv_results_mutual_info = cross_val_score(estimator=clf,
 X=ab1_minmax[:, fs_indices_mutual_info[:8]],
 y=target,
 cv=cv_method,
 scoring=scoring_metric)
cv_results_mutual_info.mean().round(4)


C:\Users\HUCON SOLUTIONS PVT\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:666: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(("The least populated class in y has only %d"
C:\Users\HUCON SOLUTIONS PVT\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:666: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(("The least populated class in y has only %d"
C:\Users\HUCON SOLUTIONS PVT\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:666: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(("The least populated class in y has only %d"


0.2025

In [86]:
plot_imp(best_features_mutual_info, feature_importances_mutual_info, 'Mutual Information', 'pink')

alt.Chart(...)

In [ ]:
#Random Forest Model

In [60]:
from sklearn.ensemble import RandomForestClassifier, ExtraTreesClassifier

In [61]:
model_rfi = RandomForestClassifier(n_estimators=100)
model_rfi.fit(ab1_minmax, target)
fs_indices_rfi = np.argsort(model_rfi.feature_importances_)[::-1][0:num_features]

In [62]:
best_features_rfi = ab1_all.columns[fs_indices_rfi].values
best_features_rfi

array(['Shell weight', 'Shucked weight', 'Whole weight', 'Viscera weight',
       'Length', 'Diameter', 'Height', 'Sex_F', 'Sex_M', 'Sex_I'],
      dtype=object)

In [63]:
feature_importances_rfi = model_rfi.feature_importances_[fs_indices_rfi]
feature_importances_rfi

array([0.16265237, 0.15355083, 0.14991391, 0.1480885 , 0.11618823,
       0.11566623, 0.10279527, 0.01814958, 0.01801308, 0.01498201])

In [87]:
plot_imp(best_features_rfi, feature_importances_rfi, 'Random Forest', 'green')

alt.Chart(...)

In [89]:
cv_results_rfi = cross_val_score(estimator=clf,
 X=ab1_minmax[:, fs_indices_rfi[:5]],
 y=target,
 cv=cv_method,
 scoring=scoring_metric)
cv_results_rfi.mean().round(4)

C:\Users\HUCON SOLUTIONS PVT\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:666: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(("The least populated class in y has only %d"
C:\Users\HUCON SOLUTIONS PVT\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:666: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(("The least populated class in y has only %d"
C:\Users\HUCON SOLUTIONS PVT\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:666: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(("The least populated class in y has only %d"


0.2116

In [96]:
from scipy import stats
print(stats.ttest_rel(cv_results_rfi, cv_results_fscore))
print(stats.ttest_rel(cv_results_rfi, cv_results_mutual_info))
print(stats.ttest_rel(cv_results_mutual_info, cv_results_fscore)) # they are equal

Ttest_relResult(statistic=2.702836791350596, pvalue=0.017161043382258018)
Ttest_relResult(statistic=2.702836791350596, pvalue=0.017161043382258018)
Ttest_relResult(statistic=nan, pvalue=nan)


In [97]:
print(stats.ttest_rel(cv_results_rfi, cv_results_full))

Ttest_relResult(statistic=3.069620795234529, pvalue=0.008319423198012177)


In [98]:
ab1_all.columns[fs_indices_rfi[:5]]

Index(['Shell weight', 'Shucked weight', 'Whole weight', 'Viscera weight',
       'Length'],
      dtype='object')

In [99]:
ab1_minmax_df = pd.DataFrame(data = ab1_minmax,columns = ab1_all.columns)

In [101]:
ab1_rfi = ab1_minmax_df[ab1_all.columns[fs_indices_rfi[:5]].values]

In [103]:
ab1_rfi = ab1_rfi.values

In [ ]:
#Hyper Parameter Tuning

In [90]:
cv_method = RepeatedStratifiedKFold(n_splits=10,
 n_repeats=3,
 random_state=4)

In [91]:
params_KNN = {'n_neighbors': [2, 4, 8, 16, 32, 64],'p': [1, 2]}

In [92]:
from sklearn.model_selection import GridSearchCV
gs_KNN = GridSearchCV(estimator=KNeighborsClassifier(),
 param_grid=params_KNN,
 cv=cv_method,
 verbose=1, # verbose: the higher, the more messages
 scoring='accuracy',
 return_train_score=True)

In [104]:
gs_KNN.fit(ab1_rfi, target);

Fitting 30 folds for each of 12 candidates, totalling 360 fits


C:\Users\HUCON SOLUTIONS PVT\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:666: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=10.
  warnings.warn(("The least populated class in y has only %d"
C:\Users\HUCON SOLUTIONS PVT\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:666: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=10.
  warnings.warn(("The least populated class in y has only %d"
C:\Users\HUCON SOLUTIONS PVT\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:666: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=10.
  warnings.warn(("The least populated class in y has only %d"


In [105]:
gs_KNN.best_params_

{'n_neighbors': 64, 'p': 1}

In [106]:
gs_KNN.best_score_

0.26949311364305684

In [107]:
results_KNN = pd.DataFrame(gs_KNN.cv_results_['params'])

In [108]:
results_KNN['test_score'] = gs_KNN.cv_results_['mean_test_score']

In [109]:
results_KNN['metric'] = results_KNN['p'].replace([1,2,3], ["Manhattan", "Euclidean", "Minkowski"
])
results_KNN

n_neighbors  p  test_score     metric
0             2  1    0.219376  Manhattan
1             2  2    0.219778  Euclidean
2             4  1    0.220813  Manhattan
3             4  2    0.218742  Euclidean
4             8  1    0.244437  Manhattan
5             8  2    0.245074  Euclidean
6            16  1    0.251536  Manhattan
7            16  2    0.254729  Euclidean
8            32  1    0.259600  Manhattan
9            32  2    0.262789  Euclidean
10           64  1    0.269493  Manhattan
11           64  2    0.269012  Euclidean

In [110]:
alt.Chart(results_KNN,
 title='KNN Performance Comparison'
 ).mark_line(point=True).encode(
 alt.X('n_neighbors', title='Number of Neighbors'),
 alt.Y('test_score', title='Mean CV Score', scale=alt.Scale(zero=False)),
 color='metric'
)

alt.Chart(...)

In [ ]:
#Decision Tree

In [112]:
from sklearn import tree
from sklearn.tree import DecisionTreeClassifier
abalone_classifier = DecisionTreeClassifier(random_state=4)
params_DT = {'criterion': ['gini', 'entropy'],
 'max_depth': [1, 2, 3, 4, 5, 6, 7, 8],
 'min_samples_split': [2, 3]}
cv_method = RepeatedStratifiedKFold(n_splits=5,
 n_repeats=3,
 random_state=999)
gs_DT = GridSearchCV(estimator=abalone_classifier,
 param_grid=params_DT,
 cv=cv_method,
 verbose=1,
 scoring='accuracy')
gs_DT.fit(ab1_rfi, target);

Fitting 15 folds for each of 32 candidates, totalling 480 fits


C:\Users\HUCON SOLUTIONS PVT\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:666: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(("The least populated class in y has only %d"
C:\Users\HUCON SOLUTIONS PVT\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:666: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(("The least populated class in y has only %d"
C:\Users\HUCON SOLUTIONS PVT\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:666: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(("The least populated class in y has only %d"


In [113]:
gs_DT.best_params_

{'criterion': 'entropy', 'max_depth': 4, 'min_samples_split': 2}

In [114]:
gs_DT.best_score_

0.2669356979820264

In [115]:
results_DT = pd.DataFrame(gs_DT.cv_results_['params'])
results_DT['test_score'] = gs_DT.cv_results_['mean_test_score']
results_DT.columns

Index(['criterion', 'max_depth', 'min_samples_split', 'test_score'], dtype='object')

In [116]:
alt.Chart(results_DT,
 title='DT Performance Comparison'
 ).mark_line(point=True).encode(
 alt.X('max_depth', title='Maximum Depth'),
 alt.Y('test_score', title='Mean CV Score', aggregate='average', scale=alt.Scale(zero=False
)),
 color='criterion'
)

alt.Chart(...)

In [117]:
#Random Forest Classifier

In [120]:
abalone_classifier = RandomForestClassifier(random_state=4)
params_RF = {'criterion': ['gini', 'entropy'],
 'max_depth': [1, 2, 3, 4, 5, 6, 7, 8],
 'min_samples_split': [2, 3]}
cv_method = RepeatedStratifiedKFold(n_splits=5,
 n_repeats=3,
 random_state=999)
gs_RF = GridSearchCV(estimator=abalone_classifier,
 param_grid=params_RF,
 cv=cv_method,
 verbose=1,
 scoring='accuracy')
gs_RF.fit(ab1_rfi, target);

Fitting 15 folds for each of 32 candidates, totalling 480 fits


C:\Users\HUCON SOLUTIONS PVT\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:666: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(("The least populated class in y has only %d"
C:\Users\HUCON SOLUTIONS PVT\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:666: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(("The least populated class in y has only %d"
C:\Users\HUCON SOLUTIONS PVT\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:666: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(("The least populated class in y has only %d"


In [121]:
gs_RF.best_params_

{'criterion': 'gini', 'max_depth': 6, 'min_samples_split': 2}

In [122]:
gs_RF.best_score_

0.27627224020857805

In [123]:
gs_RF.cv_results_['mean_test_score']

array([0.2180972 , 0.2180972 , 0.25839632, 0.25839632, 0.27140676,
       0.27140676, 0.27395983, 0.27395983, 0.27236322, 0.27292191,
       0.27627224, 0.27555482, 0.27411722, 0.2735592 , 0.27100717,
       0.2707667 , 0.21259166, 0.21259166, 0.25504455, 0.25504455,
       0.27020944, 0.27020944, 0.27363961, 0.27363961, 0.27459722,
       0.27467696, 0.27579444, 0.27547451, 0.27611447, 0.27419821,
       0.26988845, 0.26749573])

In [124]:
results_RF = pd.DataFrame(gs_RF.cv_results_['params'])
results_RF['test_score'] = gs_RF.cv_results_['mean_test_score']
results_RF.columns

Index(['criterion', 'max_depth', 'min_samples_split', 'test_score'], dtype='object')

In [125]:
alt.Chart(results_RF,
 title='RF Performance Comparison'
 ).mark_line(point=True).encode(
 alt.X('max_depth', title='Maximum Depth'),
 alt.Y('test_score', title='Mean CV Score', aggregate='average', scale=alt.Scale(zero=False
)),
 color='criterion'
)

alt.Chart(...)

In [ ]:
#GaussianNB

In [126]:
np.logspace(0,-9, num=10)

array([1.e+00, 1.e-01, 1.e-02, 1.e-03, 1.e-04, 1.e-05, 1.e-06, 1.e-07,
       1.e-08, 1.e-09])

In [129]:

from sklearn.preprocessing import PowerTransformer
ab1_power = PowerTransformer().fit_transform(ab1_unscaled)

In [130]:
ab1_power_df = pd.DataFrame(data = ab1_power,columns = ab1_all.columns)

In [131]:
ab1_power_rfi = ab1_power_df[ab1_all.columns[fs_indices_rfi[:5]].values]
ab1_power_rfi = ab1_power_rfi.values

In [132]:
from sklearn.naive_bayes import GaussianNB
nb_classifier = GaussianNB()
params_NB = {'var_smoothing': np.logspace(0,-9, num=100)}
cv_method = RepeatedStratifiedKFold(n_splits=5,
 n_repeats=3,
 random_state=999)
gs_NB = GridSearchCV(estimator=nb_classifier,
 param_grid=params_NB,
 cv=cv_method,
 verbose=1,
 scoring='accuracy')
Data_transformed = PowerTransformer().fit_transform(ab1_rfi)
gs_NB.fit(ab1_power_rfi, target);

Fitting 15 folds for each of 100 candidates, totalling 1500 fits


C:\Users\HUCON SOLUTIONS PVT\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:666: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(("The least populated class in y has only %d"
C:\Users\HUCON SOLUTIONS PVT\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:666: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(("The least populated class in y has only %d"
C:\Users\HUCON SOLUTIONS PVT\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:666: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(("The least populated class in y has only %d"


In [133]:
gs_NB.best_params_

{'var_smoothing': 0.8111308307896871}

In [134]:
gs_NB.best_score_

0.26151276394579265

In [135]:
results_NB = pd.DataFrame(gs_NB.cv_results_['params'])
results_NB['test_score'] = gs_NB.cv_results_['mean_test_score']

In [136]:
alt.Chart(results_NB,
 title='NB Performance Comparison'
 ).mark_line(point=True).encode(
 alt.X('var_smoothing', title='Var. Smoothing'),
 alt.Y('test_score', title='Mean CV Score', scale=alt.Scale(zero=False))
).interactive()

alt.Chart(...)

In [ ]:
#MLP Classifier

In [138]:
import warnings
warnings.filterwarnings('ignore')
from sklearn.neural_network import MLPClassifier
abalone_classifier = MLPClassifier(max_iter = 100)
params_MLP = {'hidden_layer_sizes': [5, 10, 20],
 'alpha': [0.0001, 0.001],
 'solver': ['sgd', 'adam'],
 'learning_rate': ['constant','adaptive']}
cv_method = RepeatedStratifiedKFold(n_splits=5,
 n_repeats=3,
 random_state=999)
gs_MLP = GridSearchCV(estimator=abalone_classifier,
 param_grid=params_MLP,
 cv=cv_method,
 verbose=1,
 scoring='accuracy')
gs_MLP.fit(ab1_rfi, target);

Fitting 15 folds for each of 24 candidates, totalling 360 fits


In [139]:
gs_MLP.best_params_

{'alpha': 0.001,
 'hidden_layer_sizes': 20,
 'learning_rate': 'constant',
 'solver': 'adam'}

In [140]:
gs_MLP.best_score_

0.2647833519563743

In [141]:
results_MLP = pd.DataFrame(gs_MLP.cv_results_['params'])
results_MLP['test_score'] = gs_MLP.cv_results_['mean_test_score']

In [142]:
results_MLP

alpha  hidden_layer_sizes learning_rate solver  test_score
0   0.0001                   5      constant    sgd    0.168545
1   0.0001                   5      constant   adam    0.227667
2   0.0001                   5      adaptive    sgd    0.172211
3   0.0001                   5      adaptive   adam    0.243316
4   0.0001                  10      constant    sgd    0.178438
5   0.0001                  10      constant   adam    0.257122
6   0.0001                  10      adaptive    sgd    0.172132
7   0.0001                  10      adaptive   adam    0.254247
8   0.0001                  20      constant    sgd    0.177161
9   0.0001                  20      constant   adam    0.261593
10  0.0001                  20      adaptive    sgd    0.182669
11  0.0001                  20      adaptive   adam    0.263506
12  0.0010                   5      constant    sgd    0.173646
13  0.0010                   5      constant   adam    0.229202
14  0.0010                   5      adaptive    sgd    0.170137
15  0.0010                   5      adaptive   adam    0.249781
16  0.0010                  10      constant    sgd    0.174127
17  0.0010                  10      constant   adam    0.254012
18  0.0010                  10      adaptive    sgd    0.175164
19  0.0010                  10      adaptive   adam    0.252016
20  0.0010                  20      constant    sgd    0.177877
21  0.0010                  20      constant   adam    0.264783
22  0.0010                  20      adaptive    sgd    0.184503
23  0.0010                  20      adaptive   adam    0.263188

In [ ]:
#Linear Regression

In [253]:
kf = KFold(n_splits=2,shuffle=False,random_state = None)

In [254]:
from sklearn.linear_model import LinearRegression, LogisticRegression, LogisticRegressionCV
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
test = []
prediction = []
model = LinearRegression()
for train_index,test_index in kf.split(ab1_rfi):
    X_train,X_test = ab1_rfi[train_index],ab1_rfi[test_index]
y_train, y_test = target.values[train_index], target.values[test_index]
model.fit(X_train, y_train)
pred = model.predict(X_test)
prediction += [pred[x] for x in range(len(pred))]
test += [y_test[x] for x in range(len(y_test))]

In [255]:
error = mean_squared_error(test,prediction)

In [256]:
print(error) 
print(error**0.5)

4.909961866246647
2.215843375838339


In [257]:
test = []
prediction = []
model = LogisticRegression()
for train_index,test_index in kf.split(ab1_rfi):
    X_train,X_test = ab1_rfi[train_index],ab1_rfi[test_index]
y_train, y_test = target.values[train_index], target.values[test_index]
model.fit(X_train, y_train)
pred = model.predict(X_test)
 
prediction += [pred[x] for x in range(len(pred))]
test += [y_test[x] for x in range(len(y_test))]

In [258]:
error = mean_squared_error(test,prediction)
print(error)
print(error**0.5)

8.177681992337165
2.8596646643159342


In [259]:
model = LogisticRegressionCV()
cv_results_logic = cross_val_score(model,ab1_rfi,target.values,cv = 5)

In [260]:
cv_results_logic.mean().round(4)

nan

In [261]:
#Model Comparision

In [264]:
cv_method_test = StratifiedKFold(n_splits=10,shuffle=True, random_state= None)
cv_results_KNN = cross_val_score(estimator=gs_KNN.best_estimator_,
 X=ab1_rfi,
 y=target,
 cv=cv_method_ttest,
 n_jobs=-2,
 scoring='accuracy')
cv_results_KNN.mean()

0.2705162186040641

In [265]:
cv_results_DT = cross_val_score(estimator=gs_DT.best_estimator_,
 X=ab1_rfi,
 y=target,
 cv=cv_method_test,
 n_jobs=-2,
 scoring='accuracy')
cv_results_DT.mean()

0.26454109439720946

In [271]:
cv_results_RF = cross_val_score(estimator=gs_RF.best_estimator_,
 X=ab1_rfi,
 y=target,
 cv=cv_method_ttest,
 n_jobs=-2,
 scoring='accuracy')
cv_results_RF.mean()

0.2709992771333173

In [272]:
cv_results_NB = cross_val_score(estimator=gs_NB.best_estimator_,
 X=ab1_power_rfi,
 y=target,
 cv=cv_method_ttest,
 n_jobs=-2,
 scoring='accuracy')
cv_results_NB.mean()

0.2635921884501967

In [273]:
cv_results_MLP = cross_val_score(estimator=gs_MLP.best_estimator_,
 X=ab1_rfi,
 y=target,
 cv=cv_method_ttest,
 n_jobs=-2,
 scoring='accuracy')
cv_results_MLP.mean()

0.263335169185226

In [274]:
print(stats.ttest_rel(cv_results_RF, cv_results_KNN))
print(stats.ttest_rel(cv_results_RF, cv_results_DT))
print(stats.ttest_rel(cv_results_RF, cv_results_NB))
print(stats.ttest_rel(cv_results_RF, cv_results_MLP))

Ttest_relResult(statistic=0.038825881816546615, pvalue=0.9698768138925684)
Ttest_relResult(statistic=0.5233734974341119, pvalue=0.6133551005400291)
Ttest_relResult(statistic=0.6571098536427962, pvalue=0.5275548775567289)
Ttest_relResult(statistic=0.6020874129609738, pvalue=0.5619754592992992)


In [277]:
pred_KNN = gs_KNN.predict(ab1_rfi)
pred_DT = gs_DT.predict(ab1_rfi)
pred_RF = gs_RF.predict(ab1_rfi)
pred_NB = gs_NB.predict(ab1_power_rfi)
pred_MLP = gs_MLP.predict(ab1_rfi)

In [279]:
from sklearn import metrics
print("\nConfusion matrix for K-Nearest Neighbor")
print(metrics.confusion_matrix(target, pred_RF))


Confusion matrix for K-Nearest Neighbor
[[  1   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   1   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0]
 [  0   0   7   8   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0]
 [  0   0   0  42   8   6   1   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0]
 [  0   0   0  12  61  22  20   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   2  22  93 112  23   5   1   0   0   1   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   2  12  25 224  94  29   4   1   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   6  13  95 259 139  52   4   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0  